#@config Configuration of the services manager for SuperNEMO Demonstrator reconstruction 4.0
logging.priority : string = "fatal"
name  : string = "SNReconstructionServices"
description  : string = "SuperNEMO Reconstruction Services Manager"
services.configuration_files : string[6] as path = \
  "@falaise:snemo/demonstrator/geometry/6.0/GeometryServices.conf" \
  "@falaise:snemo/demonstrator/db/0.1/services/DbService.conf" \
  "@falaise:snemo/demonstrator/processing/1.0/services/ContextService.conf" \
  "@falaise:snemo/demonstrator/processing/1.0/services/TrackerCellStatusService.conf" \
  "@falaise:snemo/demonstrator/processing/1.0/services/CalorimeterOmStatusService.conf" \
  "@falaise:snemo/demonstrator/processing/1.0/services/RunInfos.conf"

# end
