// ViewerGui.cc
//
// GUI interface for EventViewer class
//
//  Author: R. Beuselinck, Imperial College London
// Created: 20110704
//
// Note: the GUI part is generated by the ROOT TGuiBuilder.
//
#include "ViewerGui.h"
#include "EventViewer.h"
#include <TCanvas.h>
#include <TObject.h>

ViewerGui::ViewerGui(EventViewer* evtvwr)
: _eventViewer(evtvwr)
{
  buildGUI();
}

void ViewerGui::copyButtons(TGTextButton* next, TGTextButton* zoom,
  TGTextButton* quit)
{
  // Interface from boilerplate TGuiBuilder code to class.
  // We simply copy the generated buttons to data members.
  //
  _nextButton = next;
  _zoomButton = zoom;
  _quitButton = quit;

  // Connect up the buttons to methods
  //
  _nextButton->Connect("Clicked()", "ViewerGui", this, "doNExt()");
  _zoomButton->Connect("Clicked()", "ViewerGui", this, "doZoom()");
  _quitButton->Connect("Clicked()", "ViewerGui", this, "doQuit()");

  // Connect mouse click events in the canvas
  //
  _eventViewer->_xyCanvas->Connect("Closed()", "ViewerGui", this, "doQuit()");
  _eventViewer->_xzCanvas->Connect("Closed()", "ViewerGui", this, "doQuit()");
  _eventViewer->_xyCanvas->Connect(
    "ProcessedEvent(Int_t,Int_t,Int_t,TObject*)", "ViewerGui", this,
    "doClickXY(Int_t,Int_t,Int_t,TObject*)");
  _eventViewer->_xzCanvas->Connect(
    "ProcessedEvent(Int_t,Int_t,Int_t,TObject*)", "ViewerGui", this,
    "doClickXZ(Int_t,Int_t,Int_t,TObject*)");
}

void ViewerGui::doNExt()
{
  if (!_eventViewer->next()) doQuit();
  _eventViewer->show();
}

void ViewerGui::doZoom()
{
  _eventViewer->zoom();
}

void ViewerGui::doQuit()
{
  gApplication->Terminate();
}

void ViewerGui::doClickXY(Int_t ev, Int_t x, Int_t y, TObject* selected)
{
  _eventViewer->clickXY(ev, x, y);
}

void ViewerGui::doClickXZ(Int_t ev, Int_t x, Int_t z, TObject* selected)
{
  _eventViewer->clickXZ(ev, x, z);
}

//+ 1 ----------- start of generated gui builder code -----------
void ViewerGui::buildGUI()
{

   // main frame
   TGMainFrame *fMainFrame1325 = new TGMainFrame(gClient->GetRoot(),10,10,kMainFrame | kVerticalFrame);
   fMainFrame1325->SetName("fMainFrame1325");
   fMainFrame1325->SetLayoutBroken(kTRUE);

   // composite frame
   TGCompositeFrame *fMainFrame952 = new TGCompositeFrame(fMainFrame1325,46,80,kVerticalFrame);
   fMainFrame952->SetName("fMainFrame952");

   // vertical frame
   TGVerticalFrame *fVerticalFrame556 = new TGVerticalFrame(fMainFrame952,44,78,kVerticalFrame);
   fVerticalFrame556->SetName("fVerticalFrame556");
   TGTextButton *fTextButton918 = new TGTextButton(fVerticalFrame556,"Next");
   fTextButton918->SetTextJustify(36);
   fTextButton918->SetMargins(0,0,0,0);
   fTextButton918->SetWrapLength(-1);
   fTextButton918->Resize(40,22);
   fVerticalFrame556->AddFrame(fTextButton918, new TGLayoutHints(kLHintsLeft | kLHintsTop | kLHintsExpandX,2,2,2,2));
   TGTextButton *fTextButton919 = new TGTextButton(fVerticalFrame556,"Zoom");
   fTextButton919->SetTextJustify(36);
   fTextButton919->SetMargins(0,0,0,0);
   fTextButton919->SetWrapLength(-1);
   fTextButton919->Resize(40,22);
   fVerticalFrame556->AddFrame(fTextButton919, new TGLayoutHints(kLHintsLeft | kLHintsTop | kLHintsExpandX,2,2,2,2));
   TGTextButton *fTextButton920 = new TGTextButton(fVerticalFrame556,"Quit");
   fTextButton920->SetTextJustify(36);
   fTextButton920->SetMargins(0,0,0,0);
   fTextButton920->SetWrapLength(-1);
   fTextButton920->Resize(40,22);
   fVerticalFrame556->AddFrame(fTextButton920, new TGLayoutHints(kLHintsLeft | kLHintsTop | kLHintsExpandX,2,2,2,2));

   fMainFrame952->AddFrame(fVerticalFrame556, new TGLayoutHints(kLHintsExpandX | kLHintsExpandY,1,1,1,1));

   fMainFrame1325->AddFrame(fMainFrame952, new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
   fMainFrame952->MoveResize(0,0,46,80);

   fMainFrame1325->SetMWMHints(kMWMDecorAll,
                        kMWMFuncAll,
                        kMWMInputModeless);
   fMainFrame1325->MapSubwindows();

   fMainFrame1325->Resize(fMainFrame1325->GetDefaultSize());
   fMainFrame1325->MapWindow();
   fMainFrame1325->Resize(46,80);

   //+ ------- added by hand ----------
   copyButtons(fTextButton918, fTextButton919, fTextButton920);
}
//- 1 ----------- end of generated gui builder code -----------
