#@description A list of background radioactive decays generators (from BxDecay0 1.2.0)
#@key_label  "name"
#@meta_label "type"

[name="Ga68" type="genbb::wdecay0"]
  #@config Ga-68 decay;group=background
  decay_type    : string  = "background"
  decay_isotope : string  = "Ga68"

[name="Sc44" type="genbb::wdecay0"]
  #@config Sc-44 decay;group=background
  decay_type    : string  = "background"
  decay_isotope : string  = "Sc44"

[name="Sc44m" type="genbb::wdecay0"]
  #@config Sc-44m decay;group=background
  decay_type    : string  = "background"
  decay_isotope : string  = "Sc44m"

[name="Se83" type="genbb::wdecay0"]
  #@config Se-83 decay;group=background
  decay_type    : string  = "background"
  decay_isotope : string  = "Se83"

# end
