# The rejection ratio with respect to the total number of Bi207 generated events has been estimated
# to 2e-3 within this cuts. This generaror is provided to fasten the simulation of the calibration
# procedure, considering only events with topologies of interest. This avoid to track event of poor
# interest in the Geant4 based simulation (flsimulate).

# 2025-11-28 EC+FM : remove it from variants
[name="Bi207HighEnergyElectrons" type="genbb::poi_generator"]
  #@config Bi-207 decay generator wrapped with the Bayeux's Particles-Of-Interest selector with at least two electrons at high energy (>= 400 keV);group=obsolete
  # logging.priority : string = "debug"
  generator : string = "Bi207"
  poi.number_of_particules   : integer = 2
  poi.particule_0.type       : string = "electron"
  poi.particule_0.min_energy : real as energy = 400.0 keV
  poi.particule_1.type       : string = "electron"
  poi.particule_1.min_energy : real as energy = 400.0 keV
  # Activate recording of the original event ID to trigger the reusing of the
  # generated vertex for both time windows of the primary event
  record_original_event_id : boolean = true

# 2025-11-28 EC+FM : remove it from variants
[name="calibBi207HighEnergyElectrons" type="genbb::time_slicer_generator"]
  #@config High energy 2 electrons Bi-207 decay with time slicing;group=obsolete
  # logging.priority : string = "debug"
  generator      : string  = "Bi207HighEnergyElectrons"
  time_threshold : real as time = 100 ns
  time_cut       : real as time = 100 s
  ### Select only the delayed time window of Bi207 decays because high energy 2 electrons only occur here
  mode           : string = "both_events"
  ### 2025-11-28 EC: fix mode
  ### mode           : string = "delayed_event_only"
  # Activate recording of the original event ID to trigger the resusing of the
  # generated vertex for both time windows of the primary event
  record_original_event_id : boolean = true
