#@description The definitions for variant parameters related to the from file vertex generator
#@key_label  "name"
#@meta_label "type"

[name="from_file_vertex.filename.PM" type="parameter"]
  #@config A parameter model describing the coordinate of the vertex
  display_name        : string = "User defined vertexes filepath"
  terse_description   : string = "The filepath for input vertexes"
  mutability : string = "variable"
    variable.mode : string = "free"
  type : string = "string"
  path : boolean = true
  path.io : string = "input"
  string.default  : string = "input_vertexes.txt"


[name="from_file_vertex.VM" type="variant"]
  #@config A variant model describing the parameters for the commissioning source
  display_name       : string = "Commissioning source"
  terse_description  : string = "The configuration parameters for the commissioning source"
  parameters : string[1] = "filename"
    parameters.filename.model       : string = "from_file_vertex.filename.PM"
    parameters.filename.description : string = "The name of the file with vertexes"
 
