# List of multi-properties (datatools::multi_properties):

#@description List of SuperNEMO services (database)
#@key_label   "name"
#@meta_label  "type"


#########################################################################
[name="db" type="snemo::db_service"]

#@description SuperNEMO database service
logging.priority : string = "fatal"

#@description File path to SuperNEMO database access informations (default:
# Can be superseded by the SNDB_ACCESS_PATH environment variable
db_access : string as path = "~/.sndb.conf"

#@description File path to SuperNEMO database description
sndb_config : string as path = "@falaise:snemo/demonstrator/db/sndb/1.0/main.conf"


# end

