#@config SuperNEMO Database Service configuration sample (version 0.1)

#@description Logging level
logging.property : string = "debug"

#@description Configuration file for accessing SuperNEMO DB server
# Can be superseded with the SNDB_CONF_PATH environment variable
db_access : string as path = "~/.sndb.conf"

# #@description Hostname of the SuperNEMO DB server
# host : string = "localhost"

# #@description Hostname of the SuperNEMO DB server
# port : integer = 13319

# #@description Version of the SuperNEMO DB server
# version : string = "default"

# #@description User name for connecting the SuperNEMO DB server
# user : string = "john"

# #@description User password for connecting the SuperNEMO DB server
# password : string = "doe"

#@description Configuration file for accessing SuperNEMO DB server
# Can be superseded with the SNDB_CONF_PATH environment variable
sndb_config : string as path = "@falaise:snemo/demonstrator/db/sndb/1.0/main.conf"


# end
 




