#@description Path resolver map
#@key_label  "urn"
#@meta_label "category"

####################################################################################
# Version for Falaise <= 5.1.2 : static=2.0 + variants=2.0
####################################################################################

####################################################################################
[urn="urn:snemo:demonstrator:setup:variants:service:2.0" category="configuration"]
  #@config Main configuration file for variants service in the SuperNEMO demonstrator setup model tag 2.0
  path : string = "@falaise:snemo/demonstrator/setup/variants/service/2.0/SetupVariantRepository.conf"
  mime : string = "text/bayeux.datatools.properties"

[urn="urn:snemo:demonstrator:setup:2.0:services" category="configuration"]
  #@config Main configuration file for services in the SuperNEMO demonstrator setup model tag 2.0
  path : string = "@falaise:snemo/demonstrator/setup/2.0/SetupServices.conf"
  mime : string = "text/bayeux.datatools.properties"


####################################################################################
# 2024-06-04 FM+SP, new version for Falaise >= 5.1.3 : static=2.1 + variants=3.0
####################################################################################

[urn="urn:snemo:demonstrator:setup:variants:service:3.0" category="configuration"]
  #@config Main configuration file for variants service in the SuperNEMO demonstrator setup model tag 3.0
  path : string = "@falaise:snemo/demonstrator/setup/variants/service/3.0/SetupVariantRepository.conf"
  mime : string = "text/bayeux.datatools.properties"

[urn="urn:snemo:demonstrator:setup:2.1:services" category="configuration"]
  #@config Main configuration file for services in the SuperNEMO demonstrator setup model tag 2.1
  path : string = "@falaise:snemo/demonstrator/setup/2.1/SetupServices.conf"
  mime : string = "text/bayeux.datatools.properties"


