#!/usr/bin/env bash

resources_list_cmake="_resources.cmake"
rm -f ${resources_list_cmake}
touch ${resources_list_cmake}

cat > ${resources_list_cmake} <<EOF
set(_falaise_list_of_resources_files
EOF

find ./ -type f | grep -v "/_" | grep -v "~$" | grep -v /.svn/ | sed -e 's@^./@${CMAKE_SOURCE_DIR}/resources/@g' >> ${resources_list_cmake}

cat >> ${resources_list_cmake} <<EOF
)
EOF

exit 0
