set(Falaise_RESOURCES
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/geometry_service.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/images/bipo3-2.0_xy.jpeg
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/images/bipo3-2.0_xz.jpeg
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/bipo3.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/calibration_source.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/optical_module.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/pmt_5inch.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/setup.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/shielding_5sce_3neg_2pos_side.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/shielding_5sce_side.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/shielding_5sce_side_top.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/shielding_5sce_top.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/shielding.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/source.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/models/tb_module.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/plugins/materials.def
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/plugins/materials_plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/geant4_control/1.0/geant4_visualization.mac
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/geant4_control/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/geant4_control/1.0/processes/em.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/geant4_control/1.0/processes/particles.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/geant4_control/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/geant4_control/1.0/step_hit_processors.all_tracks.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/geant4_control/1.0/step_hit_processors.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/primary_events/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/vertexes/1.0/generators.lis
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/vertexes/1.0/images/bipo3_vertexes_1.0_source_bulk.jpeg
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/vertexes/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/vertexes/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/1.0/elements.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/1.0/materials_aliases.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/1.0/materials.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/2.0/elements.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/2.0/material_aliases.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/2.0/materials.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/2.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/2.1/elements.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/2.1/material_aliases.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/2.1/materials.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/2.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/pmt/1.0/hamamatsu_R5912MOD/hamamatsu_R5912MOD_shape.data
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/pmt/1.0/hamamatsu_R6594/hamamatsu_R6594_shape.data
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/pmt/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/background.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/calibration.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/dbd.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/misc.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.1/generators/background.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.1/generators/calibration.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.1/generators/dbd.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.1/generators/misc.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.1/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.1/variants/models/peg.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.1/variants/models/peg_generators.csv
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.1/variants/registries/primary_events.conf
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.1/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.2/generators/dbd_more.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.3/generators/dbd.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.3/generators/more_background.def
${PROJECT_SOURCE_DIR}/resources/config/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/3.0/models/tracker_drift_cell_core.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/3.0/models/tracker_drift_cell.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/3.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/4.0/models/tracker_drift_cell_core.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/4.0/models/tracker_drift_cell.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/4.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/materials/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/materials/2.0/elements.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/materials/2.0/elements.sav
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/materials/2.0/materials.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/materials/2.0/materials.sav
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/reconstruction/1.0/mock_tracker_s2c.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/mapping/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/mapping/demonstrator/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/mapping/demonstrator/detector/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/mapping/demonstrator/detector/detector.rules
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/mapping/demonstrator/electronics/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/mapping/demonstrator/electronics/electronics.rules
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/mapping/demonstrator/module.rules
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/mapping/experiment.rules
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/detector/calorimeter/calorimeter.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/detector/common/om.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/detector/def.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/detector/detector.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/detector/tracker/drift_cell.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/detector/tracker/tracker.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/boards/control_board.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/boards/febs/calo_feb.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/boards/febs/common.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/boards/febs/tracker_feb.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/boards/trigger_board.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/crates/main_calo_crate.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/crates/tracker_crate.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/crates/xg_calo_crate.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/def.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/electronics.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/racks/rack0.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/racks/rack1.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/racks/rack2.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/racks/rack3.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/racks/rack4.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/electronics/racks/rack5.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/demonstrator/module.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/models/experiment.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/devices/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/experiment/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/geometry_service.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/calorimeter_modules/calorimeter_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/calorimeter_modules/calorimeter_submodules.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/calorimeter_modules/calorimeter_walls.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/calorimeter_modules/pmt_8inch.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/calorimeter_modules/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/module_0.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/setup.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/source_module/pictures/source_foil_layout_0.pdf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/source_module/pictures/source_submodule_yz_detail.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/source_module/pictures/source_submodule_yz.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/source_module/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/source_module/source_calibration.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/source_module/source_foil_support.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/source_module/source_frame_horizontal_beams.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/source_module/source_frame_vertical_beams.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/source_module/source_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/source_module/source_strips.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/gveto.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/gveto_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/drift_cell_core.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/drift_cell_core.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/drift_cell_core.model.view_yz_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/drift_cell_node_0123.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/drift_cell_node_013.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/drift_cell_node_123.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/drift_cell_node_13.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/field_wires_set.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/gveto_line_bottom.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/gveto_line_bottom.model.view_yz_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/gveto_line_bottom.model.view_yz_2.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/gveto_line_left.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/gveto_module_inner.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/gveto_module.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/gveto_module.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/gveto_module.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/gveto_module_outer.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_frame_corner.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_front_submodule.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_front_submodule.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_front_submodule.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_front_submodule.model.view_yz_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_front_volume.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_front_volume.model.view_xy_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_front_volume.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_front_volume.model.view_yz_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_horizontal_beam_back_bottom.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_horizontal_beam_back_bottom.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_horizontal_beam_back_top.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_horizontal_beam_front_bottom.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_horizontal_beam_front_top.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_horizontal_beam_inner.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_horizontal_beam_outer.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/tracker_layer_base.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/xwall_front_right.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/xwall_front_right.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/xwall_front_right.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/xwall_front_right.model.view_yz_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/xwall_module_left.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/xwall_module_left.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pictures/xwall_module_left.rotated.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/pmt_5inch.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/tracker_layers.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/tracker_submodules.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/tracker_volumes.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/xwall.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/models/tracker_modules/xwall_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/plugins/locators_plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/plugins/magnetic_field_manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/plugins/magnetic_field_plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/plugins/magnetic_fields.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/plugins/mapping_plugins.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/plugins/materials_plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/geometry_service.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/mapping/calorimeter_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/mapping/half_commissioning_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/mapping/misc_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/mapping/setup_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/mapping/source_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/mapping/tracker_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/basic_module_0.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/basic_setup_geom_models.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/calorimeter_geom_models.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/calorimeter_modules/calo_pmt_5inch.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/calorimeter_modules/calo_pmt_8inch.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/calorimeter_modules/calorimeter_module_5inch.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/calorimeter_modules/calorimeter_module_8inch.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/calorimeter_modules/calorimeter_module_common.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/calorimeter_modules/calorimeter_submodules.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/calorimeter_modules/calorimeter_walls.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/calorimeter_modules/images/fig_calorimeter_optical_module_0.fig
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/calorimeter_modules/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/half_commissioning_setup_geom_models.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/half_module_commissioning_0.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/setup.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/shielding/shielding.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_geom_models.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/basic/source_pads.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/basic/source_strips.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/doc/ITEPfoils.xlsx
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/images/Bi207_calibration_source_carrier.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/images/source_pads-ideal.fig
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/images/source_pads-ideal.pdf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/images/source_strips-ideal.fig
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/images/source_strips-ideal.pdf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/simple/source_pads.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/simple/source_strips.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/source_blocks.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/source_calibration.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/source_foil_support.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/source_frame_horizontal_beams.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/source_frame_vertical_beams.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/source_module/source_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/tracker_geom_models.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/tracker_modules/gveto.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/tracker_modules/gveto_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/tracker_modules/pmt_5inch.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/tracker_modules/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/tracker_modules/tracker_layers.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/tracker_modules/tracker_submodules.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/tracker_modules/tracker_volumes.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/tracker_modules/xwall.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/models/tracker_modules/xwall_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/locators/plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/magnetic_field/data/csv_map_0/bintd.py
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/magnetic_field/data/csv_map_0/bintd-readme.txt
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/magnetic_field/data/csv_map_0/bmdat.py
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/magnetic_field/data/csv_map_0/MapSmoothPlusDetail.csv
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/magnetic_field/magnetic_fields.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/magnetic_field/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/magnetic_field/plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/mapping/plugins.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/materials/material_aliases.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/materials/materials.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/plugins/materials/plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/models/demonstrator.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/models/geometry.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/models/magnetic_field.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/models/shielding.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/models/source_betabeta.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/models/source_calibration.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/profiles/basic-1.0.0.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/profiles/hc-1.0.0.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/profiles/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/registries/demonstrator.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/registries/geometry.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/registries/magnetic_field.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/registries/source_betabeta.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/registries/source_calibration.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.0/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/geometry_service.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/mapping/calorimeter_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/mapping/half_commissioning_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/mapping/misc_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/mapping/setup_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/mapping/source_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/mapping/tracker_categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/plugins/materials/material_aliases.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/plugins/materials/materials.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/plugins/materials/plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/models/demonstrator.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/models/geometry.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/models/magnetic_field.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/models/shielding.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/models/source_betabeta.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/models/source_calibration.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/profiles/basic-1.0.0.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/profiles/hc-1.0.0.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/profiles/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/registries/geometry.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/registries/source_betabeta.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/4.1/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/geometry_service.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/models/source_geom_models.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/models/source_module/realistic/source_blocks.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/models/source_module/realistic/source_foils.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/plugins/materials/materials.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/plugins/materials/plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/variants/models/source_betabeta.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/variants/profiles/basic-1.0.0.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/variants/profiles/hc-1.0.0.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/variants/profiles/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/variants/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/variants/registries/geometry.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/variants/registries/source_betabeta.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/5.0/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/materials/1.0/elements.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/materials/1.0/materials.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/materials/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/1.0/mock_calorimeter_s2c.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/official-1.0.0.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/official-2.0.0.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/official_with_visu-1.0.0.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/pipeline/1.0.0/flreconstruct.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/pipeline/1.0.0/modules.defs
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/pipeline/2.0.0/flreconstruct.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/pipeline/2.0.0/modules.defs
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/pipeline/hc/1.0.0/flreconstruct.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/pipeline/hc/1.0.0/modules.defs
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/reconstruction/pipeline/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/setup/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/setup/1.0/services.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/setup/1.0/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/setup/2.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/setup/2.0/services.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/setup/2.0/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/1.0/processes/em.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/1.0/processes/particles.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/1.0/step_hit_processors-no_visu_tracks.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/1.0/step_hit_processors-only_visu_tracks.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/hit_processing/step_hit_processors-no_visu_tracks.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/hit_processing/step_hit_processors-only_visu_tracks.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/processes/em.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/processes/particles.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/sensitive/calorimeter.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/sensitive/gveto.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/sensitive/tracker.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/sensitive/xcalorimeter.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/variants/models/simulation.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/variants/profiles/default.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/variants/registries/simulation.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.0/visu/visu_0.mac
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/hit_processing/step_hit_processors-no_visu_tracks.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/hit_processing/step_hit_processors-only_visu_tracks.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/processes/em.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/processes/particles.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/sensitive/calorimeter.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/sensitive/gveto.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/sensitive/tracker.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/sensitive/xcalorimeter.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/services.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/variants/documentation/flsimulation-variant-doc.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/variants/gdm.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/variants/models/simulation.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/variants/profiles/basic-1.0.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/variants/registries/simulation.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.1/visu/visu_0.mac
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.2/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.2/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.2/variants/documentation/flsimulation-variant-doc.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.2/variants/profiles/default.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.2/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.3/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.3/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.3/services.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.3/variants/documentation/flsimulation-variant-doc.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.3/variants/gdm.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.3/variants/profiles/default.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/2.3/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/3.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/3.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/3.0/services.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/3.0/variants/documentation/flsimulation-variant-doc.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/3.0/variants/gdm.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/3.0/variants/profiles/default.profile
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/geant4_control/3.0/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.1/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.2/generators/misc.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.2/generators/versatile.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.2/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.2/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.2/variants/models/peg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.2/variants/models/peg_generators.csv
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.2/variants/registries/primary_events.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.2/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/data/energy_spectrum-example-1.data
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/generators/versatile_more.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/variants/models/peg_common_models.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/variants/models/peg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/variants/models/peg_flat_versatile_variant_models.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/variants/models/peg_generators.csv
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/variants/models/peg_tweakable_variant_models.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/variants/models/peg_versatile_variant_models.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/variants/registries/primary_events.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.3/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.4/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.4/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.4/variants/models/peg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.4/variants/models/peg_generators.csv
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.4/variants/registries/primary_events.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.4/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/hall_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/manager_2.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/scin_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/shield_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/source_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/tracker_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/hall_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/scin_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/shield_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/source_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/tracker_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/hall_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/scin_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/shield_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/source_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/tracker_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/generators/commissioning_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/generators/hall_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/generators/misc_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/generators/scin_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/generators/shield_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/generators/source_calibration_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/generators/source_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/generators/tracker_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/variants/models/half_commissioning_source.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/variants/models/versatile_spot_vertex.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/variants/models/vertexes.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/variants/models/vertexes_generators.csv
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/variants/registries/commissioning_source.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/variants/registries/vertexes.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.0/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/generators/commissioning_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/generators/hall_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/generators/misc_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/generators/om_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/generators/shielding_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/generators/source_calibration_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/generators/source_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/generators/tracker_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/variants/models/free_spot_vertex.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/variants/models/half_commissioning_source.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/variants/models/source_calibration.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/variants/models/vertexes.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/variants/models/vertexes_generators.csv
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/variants/registries/commissioning_source.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/variants/registries/vertexes.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.1/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.2/generators/om_pmt_bulk_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.2/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.2/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.2/variants/models/vertexes.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.2/variants/models/vertexes_generators.csv
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.2/variants/registries/vertexes.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/4.2/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/generators/realistic/realistic_source_pads_bulk_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/generators/realistic/realistic_source_pads_surface_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/generators/realistic/uniform_full_realistic_source_bulk_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/generators/realistic/uniform_full_realistic_source_surface_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/generators/realistic/uniform_mass_realistic_source_foils_bulk_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/generators/realistic/uniform_realistic_source_foils_surface_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/generators/realistic/uniform_se82_realistic_source_foils_bulk_vg.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/variants/models/vertexes.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/variants/models/vertexes_generators.csv
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/variants/registries/vertexes.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/5.0/variants/repository.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/geometry_service.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/mapping/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/mapping/images/drift_cell_0.fig
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/mapping/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/models/C0_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/models/C0_shape_layers.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/models/muon_trigger.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/models/setup.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/plugins/mapping_plugins.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/plugins/materials_plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/geant4_control/1.0/geant4_visualization.mac
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/geant4_control/1.0/images/snemotc_mc_muon_from_roof_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/geant4_control/1.0/images/snemotc_mc_muons_from_roof_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/geant4_control/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/geant4_control/1.0/processes/em.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/geant4_control/1.0/processes/particles.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/geant4_control/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/geant4_control/1.0/step_hit_processors-no_visu_tracks.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/geant4_control/1.0/step_hit_processors-only_visu_tracks.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/primary_events/1.0/high_energy_cosmic_rays.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/primary_events/1.0/inspector_histos_cosmic.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/primary_events/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/primary_events/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/vertexes/1.0/generators.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/vertexes/1.0/images/snemo_tc_experimental_hall_roof_vertexes.jpg
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/vertexes/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/vertexes/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/flreconstruct.conf
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/flreconstruct_inline.conf
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/flreconstruct_simple.conf
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/pipeline_modules.defs
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/README.rst
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/samples/input/flSD.brio
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/samples/input/flSD.meta
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/samples/input/flSD-vprofile.conf
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/samples/output/flRec.brio
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/samples/output/flRec.meta
${PROJECT_SOURCE_DIR}/resources/examples/flreconstruct/ex01/vprofile.conf
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/ex00/flsimulate.conf
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/ex00/README.rst
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/ex00/samples/output/flSD.brio
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/ex00/samples/output/flSD.meta
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/ex01/flsimulate.conf
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/ex01/README.rst
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/ex01/samples/output/flSD.brio
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/ex01/samples/output/flSD.meta
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/ex01/seeds.conf
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/ex01/vprofile.conf
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/legacy/ex01/README.rst
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/legacy/ex01/seeds.conf
${PROJECT_SOURCE_DIR}/resources/examples/flsimulate/legacy/ex01/vprofile.conf
${PROJECT_SOURCE_DIR}/resources/examples/geometry/ex01/ex01.cxx
${PROJECT_SOURCE_DIR}/resources/examples/geometry/ex01/README.rst
${PROJECT_SOURCE_DIR}/resources/examples/halfcommissioning/ex01/README.rst
${PROJECT_SOURCE_DIR}/resources/examples/halfcommissioning/ex01/rec.bash
${PROJECT_SOURCE_DIR}/resources/examples/halfcommissioning/ex01/rec.conf
${PROJECT_SOURCE_DIR}/resources/examples/halfcommissioning/ex01/simu.bash
${PROJECT_SOURCE_DIR}/resources/examples/halfcommissioning/ex01/simu.conf
${PROJECT_SOURCE_DIR}/resources/examples/halfcommissioning/ex01/simu.profile
${PROJECT_SOURCE_DIR}/resources/examples/variants/dummy/1.0/models/dummy.def
${PROJECT_SOURCE_DIR}/resources/examples/variants/dummy/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/examples/variants/dummy/1.0/registries/dummy2.conf
${PROJECT_SOURCE_DIR}/resources/examples/variants/dummy/1.0/registries/dummy.conf
${PROJECT_SOURCE_DIR}/resources/examples/variants/README.rst
${PROJECT_SOURCE_DIR}/resources/pipeline/snemo.demonstrator/1.0.0
${PROJECT_SOURCE_DIR}/resources/pipeline/snemo.demonstrator/1.0.0.visual
${PROJECT_SOURCE_DIR}/resources/README.rst
${PROJECT_SOURCE_DIR}/resources/urn/db/experimental_setup_infos.defs
${PROJECT_SOURCE_DIR}/resources/urn/db/experiment_infos.defs
${PROJECT_SOURCE_DIR}/resources/urn/db/README.rst
${PROJECT_SOURCE_DIR}/resources/urn/db/snemo_geometry_setup_infos.defs
${PROJECT_SOURCE_DIR}/resources/urn/db/snemo_reconstruction_setup_infos.defs
${PROJECT_SOURCE_DIR}/resources/urn/db/snemo_setup_db.conf
${PROJECT_SOURCE_DIR}/resources/urn/db/snemo_simulation_setup_infos.defs
${PROJECT_SOURCE_DIR}/resources/urn/resolvers/snemo_geometry_resource_map.conf
${PROJECT_SOURCE_DIR}/resources/urn/resolvers/snemo_reconstruction_resource_map.conf
${PROJECT_SOURCE_DIR}/resources/urn/resolvers/snemo_resource_path_resolver.conf
${PROJECT_SOURCE_DIR}/resources/urn/resolvers/snemo_setup_resource_map.conf
${PROJECT_SOURCE_DIR}/resources/urn/resolvers/snemo_simulation_resource_map.conf
)
