set(_falaise_list_of_resources_files
${PROJECT_SOURCE_DIR}/resources/config/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/materials_plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/C0_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/C0_shape_layers.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/setup.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/geometry/1.0/muon_trigger.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/control/1.0/step_hit_processor_factory.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/control/1.0/images/snemotc_mc_muons_from_roof_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/control/1.0/images/snemotc_mc_muon_from_roof_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/control/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/control/1.0/particles.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/control/1.0/em.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/control/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/control/1.0/geant4_visualization.mac
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/primary_events/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/primary_events/1.0/high_energy_cosmic_rays.def
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/primary_events/1.0/inspector_histos_cosmic.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/primary_events/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/vertexes/1.0/images/snemo_tc_experimental_hall_roof_vertexes.jpg
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/vertexes/1.0/generators.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/vertexes/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/tracker_commissioning/simulation/vertexes/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/calorimeter_modules/calorimeter_submodules.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/calorimeter_modules/calorimeter_walls.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/calorimeter_modules/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/calorimeter_modules/calorimeter_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/calorimeter_modules/pmt_8inch.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/locators_plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/source_module/pictures/source_submodule_yz.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/source_module/pictures/source_foil_layout_0.pdf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/source_module/pictures/source_submodule_yz_detail.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/source_module/source_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/source_module/source_frame_horizontal_beams.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/source_module/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/source_module/source_frame_vertical_beams.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/source_module/source_calibration.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/source_module/source_foil_support.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/source_module/source_strips.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/materials_plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/setup.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/module_0.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/tracker_volumes.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/gveto_module.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_horizontal_beam_front_bottom.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/xwall_front_right.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/drift_cell_node_13.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/drift_cell_core.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/xwall_module_left.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/xwall_front_right.model.view_yz_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_front_volume.model.view_yz_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/gveto_module.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/gveto_module_inner.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/xwall_front_right.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_horizontal_beam_back_top.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_horizontal_beam_outer.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_front_submodule.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_frame_corner.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_horizontal_beam_front_top.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_front_volume.model.view_xy_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_front_submodule.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/gveto_line_bottom.model.view_yz_2.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_front_volume.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_front_submodule.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/xwall_front_right.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/cell_dimensions.pdf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/gveto_line_left.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_horizontal_beam_back_bottom.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/xwall_inner_module.pdf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_layer_base.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/gveto_line_bottom.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/field_wires_set.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/cell_design.pdf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/drift_cell_core.model.view_yz_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_front_submodule.model.view_yz_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/gveto_module_outer.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/gveto_line_bottom.model.view_yz_1.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_horizontal_beam_back_bottom.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/drift_cell_node_0123.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/drift_cell_node_123.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/xwall_module_left.rotated.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/drift_cell_node_013.model.view_xy_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/xwall_module_left.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_horizontal_beam_inner.model.view_3d_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/drift_cell_core.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/tracker_front_volume.model.view_yz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pictures/gveto_module.model.view_xz_0.jpeg
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/pmt_5inch.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/tracker_drift_cell_nodes.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/tracker_drift_cell_base.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/xwall.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/tracker_submodules.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/gveto.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/gveto_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/tracker_layers.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/geometry/3.0/tracker_modules/xwall_module.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/primary_events/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/scin_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/tracker_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/shield_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/hall_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/3.0/source_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/scin_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/tracker_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/shield_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/hall_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/2.0/source_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/manager_2.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/scin_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/tracker_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/shield_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/hall_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/demonstrator/simulation/vertexes/1.0/source_vg.lis
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/materials/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/3.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/3.0/tracker_drift_cell_core.geom
${PROJECT_SOURCE_DIR}/resources/config/snemo/common/geometry/3.0/tracker_drift_cell.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/tb_module.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/shielding_5sce_top.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/shielding_5sce_side_top.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/source.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/bipo3.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/calibration_source.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/shielding_5sce_side.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/images/bipo3-2.0_xz.jpeg
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/images/bipo3-2.0_xy.jpeg
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/shielding_5sce_3neg_2pos_side.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/categories.lis
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/pmt_5inch.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/optical_module.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/materials_plugin.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/shielding.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/setup.geom
${PROJECT_SOURCE_DIR}/resources/config/bipo3/geometry/2.0/materials.def
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/control/1.0/step_hit_processor_factory.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/control/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/control/1.0/particles.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/control/1.0/em.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/control/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/control/1.0/step_hit_processor_factory.all_tracks.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/control/1.0/geant4_visualization.mac
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/vertexes/1.0/images/bipo3_vertexes_1.0_source_bulk.jpeg
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/vertexes/1.0/generators.lis
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/vertexes/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/bipo3/simulation/vertexes/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/pmt/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/pmt/1.0/hamamatsu_R6594/hamamatsu_R6594_shape.data
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/pmt/1.0/hamamatsu_R6594/hamamatsu_R6594.jpg
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/pmt/1.0/hamamatsu_R5912MOD/hamamatsu_R5912MOD_shape.data
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/pmt/1.0/hamamatsu_R5912MOD/hamamatsu_R5912MOD.jpg
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/1.0/elements.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/1.0/materials_aliases.def
${PROJECT_SOURCE_DIR}/resources/config/common/geometry/materials/1.0/materials.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/dbd.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/misc.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/manager.conf
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/README.rst
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/calibration.def
${PROJECT_SOURCE_DIR}/resources/config/common/simulation/primary_events/1.0/background.def
${PROJECT_SOURCE_DIR}/resources/README.rst
)
