set(_falaise_list_of_resources_files
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/tracker_commissioning/1.0/categories.lis
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/tracker_commissioning/1.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/tracker_commissioning/1.0/README.rst
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/tracker_commissioning/1.0/materials_plugin.conf
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/tracker_commissioning/1.0/C0_module.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/tracker_commissioning/1.0/C0_shape_layers.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/tracker_commissioning/1.0/setup.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/tracker_commissioning/1.0/muon_trigger.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/calorimeter_modules/calorimeter_submodules.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/calorimeter_modules/calorimeter_walls.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/calorimeter_modules/README.rst
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/calorimeter_modules/calorimeter_module.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/calorimeter_modules/pmt_8inch.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/categories.lis
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/locators_plugin.conf
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/pictures/foil_roller.gp
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/pictures/source_submodule_yz.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/pictures/source_foil_layout_0.fig
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/pictures/source_foil_layout_0.pdf
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/pictures/source_submodule_yz_detail.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/source_module.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/source_frame_horizontal_beams.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/README.rst
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/source_frame_vertical_beams.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/source_calibration.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/source_foil_support.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/source_strips.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/source_module/source_foil_support.geom.pool
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/README.rst
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/materials_plugin.conf
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/setup.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/module_0.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/tracker_volumes.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/gveto_module.model.view_yz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_horizontal_beam_front_bottom.model.view_xz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/xwall_front_right.model.view_xy_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/drift_cell_node_13.model.view_xy_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/cell_design.fig
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/drift_cell_core.model.view_3d_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/xwall_module_left.model.view_xz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/xwall_front_right.model.view_yz_1.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_front_volume.model.view_yz_1.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/gveto_module.model.view_xy_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/gveto_module_inner.model.view_3d_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/xwall_front_right.model.view_xz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_horizontal_beam_back_top.model.view_xz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_horizontal_beam_outer.model.view_3d_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_front_submodule.model.view_yz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/cell_dimensions.fig
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_frame_corner.model.view_3d_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_horizontal_beam_front_top.model.view_xz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_front_volume.model.view_xy_1.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_front_submodule.model.view_xy_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/gveto_line_bottom.model.view_yz_2.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_front_volume.model.view_xy_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_front_submodule.model.view_xz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/xwall_front_right.model.view_yz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/cell_dimensions.pdf
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/gveto_line_left.model.view_yz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_horizontal_beam_back_bottom.model.view_xz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/xwall_inner_module.pdf
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/cell_design.gp
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_layer_base.model.view_xy_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/gveto_line_bottom.model.view_yz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/field_wires_set.model.view_3d_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/cell_design.pdf
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/drift_cell_core.model.view_yz_1.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_front_submodule.model.view_yz_1.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/gveto_module_outer.model.view_yz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/gveto_line_bottom.model.view_yz_1.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_horizontal_beam_back_bottom.model.view_yz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/drift_cell_node_0123.model.view_xy_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/drift_cell_node_123.model.view_xy_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/xwall_module_left.rotated.model.view_3d_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/drift_cell_node_013.model.view_xy_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/xwall_module_left.model.view_3d_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_horizontal_beam_inner.model.view_3d_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/xwall_inner_module.fig
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/drift_cell_core.model.view_yz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/tracker_front_volume.model.view_yz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pictures/gveto_module.model.view_xz_0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/pmt_5inch.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/tracker_drift_cell_nodes.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/tracker_drift_cell_base.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/xwall.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/tracker_submodules.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/gveto.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/README.rst
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/gveto_module.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/tracker_layers.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/demonstrator/3.0/tracker_modules/xwall_module.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/common/materials/1.0/README.rst
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/common/3.0/README.rst
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/common/3.0/tracker_drift_cell_core.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/snemo/common/3.0/tracker_drift_cell.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/tb_module.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/shielding_5sce_top.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/shielding_5sce_side_top.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/source.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/bipo3.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/calibration_source.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/shielding_5sce_side.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/shielding_5sce_3neg_2pos_side.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/categories.lis
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/pmt_5inch.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/optical_module.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/README.rst
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/shielding.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/setup.geom
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/bipo3-2.0.jpeg
${CMAKE_SOURCE_DIR}/resources/config/geometry/bipo3/2.0/materials.def
${CMAKE_SOURCE_DIR}/resources/config/geometry/common/pmt/README.rst
${CMAKE_SOURCE_DIR}/resources/config/geometry/common/pmt/hamamatsu_R6594/hamamatsu_R6594_shape.data
${CMAKE_SOURCE_DIR}/resources/config/geometry/common/pmt/hamamatsu_R6594/hamamatsu_R6594.jpg
${CMAKE_SOURCE_DIR}/resources/config/geometry/common/pmt/hamamatsu_R5912MOD/hamamatsu_R5912MOD_shape.data
${CMAKE_SOURCE_DIR}/resources/config/geometry/common/pmt/hamamatsu_R5912MOD/hamamatsu_R5912MOD.jpg
${CMAKE_SOURCE_DIR}/resources/config/geometry/common/materials/1.0/elements.def
${CMAKE_SOURCE_DIR}/resources/config/geometry/common/materials/1.0/README.rst
${CMAKE_SOURCE_DIR}/resources/config/geometry/common/materials/1.0/materials_aliases.def
${CMAKE_SOURCE_DIR}/resources/config/geometry/common/materials/1.0/materials.def
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/tracker_commissioning/primary_events/1.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/tracker_commissioning/primary_events/1.0/high_energy_cosmic_rays.def
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/tracker_commissioning/primary_events/1.0/inspector_histos_cosmic.conf
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/tracker_commissioning/primary_events/1.0/README.rst
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/tracker_commissioning/vertexes/1.0/generators.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/tracker_commissioning/vertexes/1.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/tracker_commissioning/vertexes/1.0/README.rst
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/primary_events/1.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/3.0/scin_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/3.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/3.0/tracker_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/3.0/shield_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/3.0/hall_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/3.0/source_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/2.0/scin_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/2.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/2.0/tracker_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/2.0/shield_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/2.0/hall_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/2.0/source_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/1.0/manager_2.conf
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/1.0/scin_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/1.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/1.0/tracker_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/1.0/shield_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/1.0/hall_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/snemo/demonstrator/vertexes/1.0/source_vg.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/bipo3/vertexes/1.0/generators.lis
${CMAKE_SOURCE_DIR}/resources/config/simulation/bipo3/vertexes/1.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/simulation/common/primary_events/1.0/dbd.def
${CMAKE_SOURCE_DIR}/resources/config/simulation/common/primary_events/1.0/misc.def
${CMAKE_SOURCE_DIR}/resources/config/simulation/common/primary_events/1.0/manager.conf
${CMAKE_SOURCE_DIR}/resources/config/simulation/common/primary_events/1.0/README.rst
${CMAKE_SOURCE_DIR}/resources/config/simulation/common/primary_events/1.0/calibration.def
${CMAKE_SOURCE_DIR}/resources/config/simulation/common/primary_events/1.0/background.def
${CMAKE_SOURCE_DIR}/resources/README.rst
)
