#@description The SuperNEMO demonstrator service for OM status
#@key_label   "name"
#@meta_label  "type"

[name="calorimeterOmECalibStatus" type="snemo::calorimeter_om_status_service"]

#@description Verbosity
logging.priority : string  = "debug"

#@description The name of the official geometry service
geometry_label : string = "geometry"

#@description The mode of the calorimeter OM status service (supported: "files", "db")
mode : string = "db"

#@description The name of the official DB service
db_label : string = "db"     

#@description The name of the DB table which contains OM status change events
db.table_name : string = "OM_Status_Change_Events"



# end