#@description List of SuperNEMO services (run informations)
#@key_label   "name"
#@meta_label  "type"


#########################################################################
[name="runInfo" type="snemo::run_info_service"]

#@description SuperNEMO run info service
logging.priority : string = "fatal"

#@description Access mode to run informations
mode : string = "db"

#@description Identifier of the database service
db_label : string = "db"

run_infos.table_name : string = "Run_infos"

run_phases.table_name : string = "Run_phases"

# end
