#@description The SuperNEMO demonstrator service for tracker cell status
#@key_label   "name"
#@meta_label  "type"

[name="trackerCellStatus" type="snemo::tracker_cell_status_service"]

#@description Verbosity
logging.priority : string  = "debug"

#@description The name of the official geometry service
geometry_label : string = "geometry"

#@description The mode of the calorimeter OM status service (supported: "files", "db")
mode : string = "db"

#@description The name of the official DB service
db_label : string = "db"     

#@description The name of the DB table which contains OM status change events
db.table_name : string = "GG_Status_Change_Events"


# 2026-07-13 FM, OBSOLETE:
# #@description The mode of the tracker cell status service (supported: "files", "db")
# # Here we use the "files" mode which means we load a list of tracker cells' status
# # from some hardcoded files distributed within Falaise.
# # Mode "db" means the service will use the "Db" database service to fetch tracker cell's status. This is not supported yet (2022-11-29).
# mode : string = "files"
# files.cell_maps : string[1] as path = \
#   "@falaise:snemo/demonstrator/reconstruction/db/tracker_cell_status-1.map"

# end
