#@description The SuperNEMO demonstrator service for tracker cell plasma propagation times (PPT)
#@key_label   "name"
#@meta_label  "type"

[name="trackerCellPPT" type="snemo::tracker_cell_ppt_service"]

#@description Verbosity
logging.priority : string  = "debug"

#@description The mode of the calorimeter OM status service (supported: "files", "db")
mode : string = "db"

#@description The name of the official DB service
db_label : string = "db"     

#@description Name of the tracker cell status service
tracker_cell_status_label : string = "trackerCellStatus"

#@description The name of the DB table which contains tracker cell PPT informations
db.table_name : string = "GG_PPT"


# end
