#@description Definition list of URNs associated to SuperNEMO project
#@key_label  "urn"
#@meta_label "category"


####################################################################################
# Version for Falaise >= 5.1.8 : static=3.0 + variants=4.0
####################################################################################


##################################
# SETUP VARIANTS SERVICE TAG 4.0
#

[urn="urn:snemo:demonstrator:setup:variants:service:4.0" category="varservice"]
  description : string = "SuperNEMO demonstrator setup variants service"
  topics : string[3] = "registries" "profiles" "defprofile"
  topic.registries.components : string[1] = \
    "urn:snemo:demonstrator:geometry:variants:4.0"
  topic.profiles.components   : string[1] = \
    "urn:snemo:demonstrator:geometry:variants:service:4.0:profiles:basic-1.0"
  topic.defprofile.component  : string = \
    "urn:snemo:demonstrator:geometry:variants:service:4.0:profiles:default"


############################
# SETUP TAG 3.0
#

[urn="urn:snemo:demonstrator:setup:3.0:services" category="services"]
  description : string  = "Services setup for the SuperNEMO demonstrator detector setup (tag 3.0)"
  topics : string[1] = "geometry"
  topic.geometry.component : string  = "urn:snemo:demonstrator:geometry:6.0"

[urn="urn:snemo:demonstrator:setup:3.0" category="expsetup"]
  description : string = "SuperNEMO demonstrator detector setup (tag 3.0)"
  #@description Dependencies
  topics : string[3] = "variants" "geometry" "services"
  topic.variants.components : string[1] = "urn:snemo:demonstrator:setup:variants:service:4.0"
  topic.geometry.component  : string    = "urn:snemo:demonstrator:geometry:6.0"
  topic.services.component  : string    = "urn:snemo:demonstrator:setup:3.0:services"


# end