#@description A list of vertex generators
#@key_label   "name"
#@meta_label  "type"

[name="from_file" type="genvtx::from_file_vg"]
#@variant_section_only vertexes:generator/if_from_file|false
#@config Vertex generation from an input text file
time_generator : boolean = false
filename : string =  @variant(vertexes:generator/if_from_file/filename|"input_vertexes.txt")
length_unit : string = "mm"

[name="experimental_hall_french_wall" type="genvtx::box_model_vg"]
#@config Vertex generation from the french wall surface of the experimental hall
  logging.priority  : string = "notice"
  origin : string  = "category='hall' hall={0}"
  mode   : string  = "surface"
    mode.surface.front    : boolean = 1
    mode.surface.skin_skip : real as length = -1.0 cm

[name="experimental_hall_italian_wall" type="genvtx::box_model_vg"]
#@config Vertex generation from the italian wall surface of the experimental hall
  logging.priority  : string = "notice"
  origin : string  = "category='hall' hall={0}"
  mode   : string  = "surface"
    mode.surface.back    : boolean = 1
    mode.surface.skin_skip : real as length = -1.0 cm

[name="experimental_hall_mountain_wall" type="genvtx::box_model_vg"]
#@config Vertex generation from the mountain wall surface of the experimental hall
  logging.priority  : string = "notice"
  origin : string  = "category='hall' hall={0}"
  mode   : string  = "surface"
    mode.surface.left    : boolean = 1
    mode.surface.skin_skip : real as length = -1.0 cm

[name="experimental_hall_tunnel_wall" type="genvtx::box_model_vg"]
#@config Vertex generation from the tunnel wall surface of the experimental hall
  logging.priority  : string = "notice"
  origin : string  = "category='hall' hall={0}"
  mode   : string  = "surface"
    mode.surface.right    : boolean = 1
    mode.surface.skin_skip : real as length = -1.0 cm

