#@description A list of vertex generators
#@key_label   "name"
#@meta_label  "type"


[name="calo_curtain_bulk" type="genvtx::box_model_vg"]
#@config Vertex generation from the bulk volume of the wrapper of all main calorimeter scintillator blocks
  logging.priority : string = "warning"
  origin : string  = "category='calorimeter_curtain' module={*} side={*} column={*} row={*}"
  mode   : string  = "bulk"


[name="calo_curtain_surface_front" type="genvtx::box_model_vg"]
#@config Vertex generation from the surface of the wrapper of all main calorimeter scintillator blocks
  logging.priority : string = "warning"
  origin : string  = "category='calorimeter_curtain' module={*} side={*} column={*} row={*}"
  mode   : string  = "surface"
    mode.surface.top  : boolean = 1


[name="calo_curtain_surface_back" type="genvtx::box_model_vg"]
#@config Vertex generation from the surface of the wrapper of all main calorimeter scintillator blocks
  logging.priority : string = "warning"
  origin : string  = "category='calorimeter_curtain' module={*} side={*} column={*} row={*}"
  mode   : string  = "surface"
    mode.surface.bottom : boolean = 1
 