#@description A list of vertex generators
#@key_label   "name"
#@meta_label  "type"

[name="from_file" type="genvtx::from_file_vg"]
#@variant_section_only vertexes:generator/if_from_file|false
#@config Vertex generation from an input text file
time_generator : boolean = false
filename : string =  @variant(vertexes:generator/if_from_file/filename|"input_vertexes.txt")
length_unit : string = "mm"