#@description A list of descriptions for DB
#@key_label  "name"
#@meta_label "type"


#####################################################################
[name="PrimaryIntKeyFieldDesc" type="field_description"]
#config A generic unique ID of a table record (example: "42")
type       : string = "integer"
max_length : integer = 32
unsigned   : boolean = true


#####################################################################
[name="InstanceIdFieldDesc" type="field_description"]
#config The unique ID of the configuration of a process (example: "trigger:42")
type       : string = "var_str"
max_length : integer = 20


#####################################################################
[name="ModelIdFieldDesc" type="field_description"]
#config The unique ID of the configuration of a process (example: "model-1.2.3")
type       : string = "var_str"
max_length : integer = 20


#####################################################################
[name="DescriptionFieldDesc" type="field_description"]
#config A comment (example: "dummy object")
type       : string = "var_str"
max_length : integer = 100


#####################################################################
[name="CommentFieldDesc" type="field_description"]
#config A comment (example: "dummy object")
type       : string = "var_str"
max_length : integer = 100


#####################################################################
[name="ConfigurationIdFieldDesc" type="field_description"]
#config The unique ID of the configuration of a process (example: "trigger-123")
type       : string = "var_str"
max_length : integer = 20


#####################################################################
[name="DateTimeFieldDesc" type="field_description"]
#config A date time value in UTC convention (example: "2025-04-10 12:34:56.789012")
type       : string = "datetime"


#####################################################################
[name="TimeDurationFieldDesc" type="field_description"]
#config A time duration in seconds and fractional seconds (example: 12234.567890)
type       : string = "real"
unsigned   : boolean = true


#####################################################################
[name="StatusBit16FieldDesc" type="field_description"]
#config A 16-bit bitset describing the status of a process or system (example: "0100001010100011")
type       : string = "bitset"
max_length : integer = 16


#####################################################################
[name="NumberOfItemsFieldDesc" type="field_description"]
#config A number of items in a list (example: 42)
type       : string = "integer"
unsigned   : boolean = true


#####################################################################
[name="JsonFieldDesc" type="field_description"]
#config A JSON object (example: '{ "a" : 42 , "b" : "foo", "c" : True }')
type       : string = "json"


#####################################################################
[name="VersionCountFieldDesc" type="field_description"]
#config A version integer number (example: 42)
type       : string = "integer"
unsigned   : boolean = true



# end
