#@description A list of descriptions for DB tracker
#@key_label  "name"
#@meta_label "type"


#####################################################################
[name="OmNumberFieldDesc" type="field_description"]

type       : string = "integer"
unsigned   : boolean = true
