#@description A list of descriptions for DB tracker cell PPT table (Plasma Propagation Time)
#@key_label  "name"
#@meta_label "type"


#####################################################################
[name="GgPptTypeFieldDesc" type="field_description"]

type       : string = "var_str"
max_length : integer = 32


#####################################################################
[name="GgPptFieldDesc" type="field_description"]

type       : string = "real"
unsigned   : boolean = true


#####################################################################
[name="GgPptErrorFieldDesc" type="field_description"]

type       : string = "real"
unsigned   : boolean = true



#####################################################################
[name="GgPptTableDesc" type="table_description"]

fields : string[7] = \
  "id" \
  "cell_num" \
  "start_time" \
  "stop_time" \
  "ppt_type" \
  "ppt" \
  "ppt_error"

fields.id.comment : string = "record_id"
fields.id.model   : string = "PrimaryIntKeyFieldDesc"

fields.cell_num.comment : string = "Cell number"
fields.cell_num.model   : string = "GgNumberFieldDesc"

fields.start_time.comment : string = "Event timestamp"
fields.start_time.model   : string = "DateTimeFieldDesc"

fields.stop_time.comment : string = "Event timestamp"
fields.stop_time.model   : string = "DateTimeFieldDesc"

fields.ppt_type.comment : string = "Geiger cell PPT type"
fields.ppt_type.model   : string = "GgPptTypeFieldDesc"

fields.ppt.comment : string = "Geiger cell PPT value (nanosecond)"
fields.ppt.model   : string = "GgPptFieldDesc"

fields.ppt_error.comment : string = "Geiger cell PPT uncertainty value (nanosecond)"
fields.ppt_error.model   : string = "GgPptErrorFieldDesc"

# end
