#@description A list of descriptions for DB
#@key_label  "name"
#@meta_label "type"


#####################################################################
[name="GgEventIDFieldDesc" type="field_description"]

type       : string = "integer"
unsigned   : boolean = true

#####################################################################
[name="GgEventTypeFieldDesc" type="field_description"]

type       : string = "var_str"
max_length : integer = 32


#####################################################################
[name="GgStatusBitFieldDesc" type="field_description"]

type       : string = "var_str"
max_length : integer = 32


#####################################################################
[name="GgStatusChangeEventsTableDesc" type="table_description"]

fields : string[5] = \
  "event_id" \
  "cell_num" \
  "timestamp" \
  "event_type" \
  "bit"

fields.event_id.comment : string = "Event ID"
fields.event_id.model   : string = "GgEventIDFieldDesc"
fields.event_id.primary_key : boolean = true

fields.cell_num.comment : string = "Cell number"
fields.cell_num.model   : string = "GgNumberFieldDesc"

fields.timestamp.comment : string = "Event timestamp"
fields.timestamp.model   : string = "DateTimeFieldDesc"

fields.event_type.comment : string = "Event type"
fields.event_type.model   : string = "GgEventTypeFieldDesc"

fields.bit.comment : string = "Cell status bit"
fields.bit.model   : string = "GgStatusBitFieldDesc"


# end