#@description A list of descriptions for DB OM energy calibration table
#@key_label  "name"
#@meta_label "type"


#####################################################################
[name="OmEnergyCalibTypeFieldDesc" type="field_description"]

type       : string = "var_str"
max_length : integer = 32


#####################################################################
[name="OmEnergyCalibrationTableDesc" type="table_description"]

fields : string[7] = \
  "id" \
  "om_num" \
  "start_time" \
  "stop_time" \
  "calib_type" \
  "calib_version" \
  "calib_params"
  
fields.id.comment : string = "record_id"
fields.id.model   : string = "PrimaryIntKeyFieldDesc"

fields.om_num.comment : string = "OM number"
fields.om_num.model   : string = "GgNumberFieldDesc"

fields.start_time.comment : string = "Event timestamp"
fields.start_time.model   : string = "DateTimeFieldDesc"

fields.stop_time.comment : string = "Event timestamp"
fields.stop_time.model   : string = "DateTimeFieldDesc"

fields.calib_type.comment : string = "OM energy calibration method"
fields.calib_type.model   : string = "OmEnergyCalibTypeFieldDesc"

fields.calib_version.comment : string = "OM energy calibration version"
fields.calib_version.model   : string = "VersionCountFieldDesc"

fields.calib_params.comment : string = "OM energy calibration parameters"
fields.calib_params.model   : string = "JsonFieldDesc"

# end
