#@description A list of descriptions for DB
#@key_label  "name"
#@meta_label "type"


#####################################################################
[name="RunNumberFieldDesc" type="field_description"]

type       : string = "integer"
unsigned   : boolean = true
max_length : integer = 10


#####################################################################
[name="RunCategoryFieldDesc" type="field_description"]

type       : string = "integer"
unsigned   : boolean = true


#####################################################################
[name="RunInfosTableDesc" type="table_description"]

fields : string[5] = \
  "run_number" \
  "run_category" \
  "start_time" \
  "duration" \
  "status"

fields.run_number.comment : string = "Run number"
fields.run_number.model   : string = "RunNumberFieldDesc"
fields.run_number.primary_key : boolean = true

fields.run_category.comment : string = "Run type"
fields.run_category.model   : string = "RunCategoryFieldDesc"

fields.start_time.comment : string = "Run start datetime"
fields.start_time.model   : string = "DateTimeFieldDesc"

fields.duration.comment : string = "Run duration (second)"
fields.duration.model   : string = "TimeDurationFieldDesc"

fields.status.comment : string = "Run status bits"
fields.status.model   : string = "StatusBit16FieldDesc"


# end