#@description A list of descriptions for DB
#@key_label  "name"
#@meta_label "type"


#####################################################################
[name="RunPhaseNumberFieldDesc" type="field_description"]
#config The ID of a run phase
type       : string = "integer"
unsigned   : boolean = true
max_length : integer = 10


#####################################################################
[name="RunPhasesTableDesc" type="table_description"]
#config The table describing run phases

fields : string[5] = \
  "phase_id" \
  "start_time" \
  "stop_time" \
  "status" \
  "comment" 

fields.phase_id.text        : string = "Unique phase ID"
fields.phase_id.model       : string = "RunPhaseNumberFieldDesc"
fields.phase_id.primary_key : boolean = true

fields.start_time.text  : string = "Start time"
fields.start_time.model : string = "DateTimeFieldDesc"

fields.stop_time.text         : string = "Stop time"
fields.stop_time.model        : string = "DateTimeFieldDesc"
fields.stop_time.null_allowed : boolean = true

fields.status.text  : string = "Phase status bits"
fields.status.model : string = "StatusBit16FieldDesc"

fields.comment.text         : string = "Optional comment"
fields.comment.model        : string = "CommentFieldDesc"
fields.comment.null_allowed : boolean = true


# end