#@description A list of background radioactive decays generators
#@key_label  "name"
#@meta_label "type"


#####################################################################
[name="RunDbDatabaseDesc" type="database_description"]

tables : string[10] = \
  "Dataset_models" \
  "DatasetProducer_models" \
  "DatasetProducers" \
  "Datasets" \
  "Run_phases" \
  "Run_infos" \
  "GG_Status_Change_Events" \
  "OM_Status_Change_Events" \
  "GG_PPT" \
  "OM_Energy_Calib" 

tables.Dataset_models.text  : string = "Table of dataset models"
tables.Dataset_models.model : string = "DatasetModelsTableDesc"

tables.DatasetProducer_models.text  : string = "Table of dataset producer models"
tables.DatasetProducer_models.model : string = "DatasetProducerModelsTableDesc"

tables.DatasetProducers.text  : string = "Table of dataset producers"
tables.DatasetProducers.model : string = "DatasetProducersTableDesc"

tables.Datasets.text  : string = "Table of datasets"
tables.Datasets.model : string = "DatasetsTableDesc"

tables.Run_phases.text  : string = "Table of run phases"
tables.Run_phases.model : string = "RunPhasesTableDesc"

tables.Run_infos.text  : string = "Table of run infos"
tables.Run_infos.model : string = "RunInfosTableDesc"

tables.GG_Status_Change_Events.text  : string = "Table of tracker cell status change events"
tables.GG_Status_Change_Events.model : string = "GgStatusChangeEventsTableDesc"

tables.OM_Status_Change_Events.text  : string = "Table of OM status change events"
tables.OM_Status_Change_Events.model : string = "OmStatusChangeEventsTableDesc"

tables.GG_PPT.text  : string = "Table of tracker cell PPT records"
tables.GG_PPT.model : string = "GgPptTableDesc"

tables.OM_Energy_Calib.text  : string = "Table of OM energy calibration records"
tables.OM_Energy_Calib.model : string = "OmEnergyCalibrationTableDesc"


# end
