#@config SNDB main configuration for the description of SuperNEMO databases

#@description List of config files for databases' descriptions
database_descriptions.files : string[5] as path = \
  "@falaise:snemo/demonstrator/db/sndb/1.0/rundb/base_field_types.conf" \
  "@falaise:snemo/demonstrator/db/sndb/1.0/rundb/dataset_tables.conf" \
  "@falaise:snemo/demonstrator/db/sndb/1.0/rundb/run_phases_table.conf" \
  "@falaise:snemo/demonstrator/db/sndb/1.0/rundb/run_infos_table.conf" \
  "@falaise:snemo/demonstrator/db/sndb/1.0/rundb/rundb.conf"

#@description List of databases
databases : string[1] = "nemo_rundb" 

# Characteristics of the 'rundb' database:
databases.nemo_rundb.text  : string = "SuperNEMO run database (official)"
databases.nemo_rundb.model : string = "RunDbDatabaseDesc"

# # Characteristics of the 'rundbdev' database:
# databases.nemo_rundbdev.text  : string = "SuperNEMO run database (debug)"
# databases.nemo_rundbdev.model : string = "RunDbDatabaseDesc"

# end
