#@configuration SuperNEMO common service manager
name        : string = "flCommonServices"
description : string = "SuperNEMO Demonstrator Service manager for SuperNEMO processing"
services.configuration_files : string[8] as path = \
  "@falaise:snemo/demonstrator/geometry/6.0/GeometryServices.conf" \
  "@falaise:snemo/demonstrator/db/0.1/services/DbService.conf" \
  "@falaise:snemo/demonstrator/processing/1.0/services/ContextService.conf" \
  "@falaise:snemo/demonstrator/processing/1.0/services/TrackerCellStatusService.conf" \
  "@falaise:snemo/demonstrator/processing/1.0/services/CalorimeterOmStatusService.conf" \
  "@falaise:snemo/demonstrator/processing/1.0/services/TrackerCellPPTService.conf" \
  "@falaise:snemo/demonstrator/processing/1.0/services/CalorimeterOmECalibService.conf" \
  "@falaise:snemo/demonstrator/processing/1.0/services/RunInfos.conf"
 
# end
