# Informations to access the SuperNEMO MariaDB server 
# from Falaise run from a CCIN2P3 cluster's node:
host=ccmyga02.in2p3.fr
port=3319
database=nemo_rundb
user=nemo_user
password=nemo_password
# end
