
[name="calorimeter_main_scin_block" type="geomtools::box"]
  x           : real as length = 236.0 mm
  y           : real as length = 236.0 mm
  z           : real as length = 163.0 mm


[name="calorimeter_8inch_scin_block_extrusion" type="geomtools::polycone"]
build_mode  : string = "datafile"
datafile : string as path = "@falaise:geometry/PMT/hamamatsu_R5912MOD_shape-front.data"
datafile.columns : string = "ignore_rmin"
# zmin : real as length = 30.0 mm
# zmax : real as length = 80.0 mm


[name="calorimeter_8inch_scin_block_extruded" type="geomtools::subtraction_3d"]

first_shape.name       : string = "calorimeter_main_scin_block"
second_shape.name      : string = "calorimeter_8inch_scin_block_extrusion"
second_shape.placement : string = "0.0 0.0 -124.5 (mm)"


[name="calorimeter_5inch_scin_block_extrusion" type="geomtools::polycone"]
build_mode  : string = "datafile"
datafile : string as path = "@falaise:geometry/PMT/hamamatsu_R6594_shape-front.data"
datafile.columns : string = "ignore_rmin"
# zmin : real as length = 30.0 mm
# zmax : real as length = 80.0 mm


[name="calorimeter_5inch_scin_block_extruded" type="geomtools::subtraction_3d"]

first_shape.name       : string = "calorimeter_main_scin_block"
second_shape.name      : string = "calorimeter_5inch_scin_block_extrusion"
second_shape.placement : string = "0.0 0.0 -133.0 (mm)"


# end
