#@config The variants configuration for the SuperNEMO demonstrator reconstruction 3.1
name              : string = "reconstruction"
display_name      : string = "SuperNEMO demonstrator reconstruction variant repository"
terse_description : string = "SuperNEMO demonstrator reconstruction configuration parameters"
logging.priority  : string = "fatal"
organization : string    = "snemo"
application  : string    = "falaise"
registries   : string[1] = "geometry"
registries.geometry.config : string as path = \
  "@falaise:snemo/demonstrator/geometry/variants/3.0/GeometryVariants.conf"
registries.geometry.rank   : integer = 0
lock : boolean = true

