# -*- mode: conf-unix; -*-
# Author : F.Mauger
# Date   : June 2026

#@description A list of vertex generators
#@key_label   "name"
#@meta_label  "type"

[name="real_snrs1_source_strip_itep_pad_surface_back_test" type="snrs::mesh_pad_vg"]
#@config Vertex generation from both surfaces of the SuperNEMO source strip X pad 0;group=SourceFoilRealistic/SNRS1;rank=second

#@description Geometry version requirement (not working with version lower than 5.0)
geometry.setup_requirement : string = "snemo::demonstrator(>=5)"
origin         : string = " category='source_pad' module={0} strip={3} pad={0} "
mode           : string = "surface"
skin_thickness : real as length = 1 um
back_side      : boolean = true
front_side     : boolean = false  
skin_skip      : real as length = 1 um 

logging.priority : string = "debug"

# TEST
tiles.min_row    : integer = 50
tiles.max_row    : integer = 51
tiles.min_column : integer = 4
tiles.max_column : integer = 6
tiles.part_0     : boolean = true
tiles.part_1     : boolean = false

[name="real_snrs1_source_strip_itep_pad_surface_front_test" type="snrs::mesh_pad_vg"]
#@config Vertex generation from both surfaces of the SuperNEMO source strip X pad 0;group=SourceFoilRealistic/SNRS1;rank=second

#@description Geometry version requirement (not working with version lower than 5.0)
geometry.setup_requirement : string = "snemo::demonstrator(>=5)"
origin         : string = " category='source_pad' module={0} strip={3} pad={0} "
mode           : string = "surface"
skin_thickness : real as length = 1 um
back_side      : boolean = false
front_side     : boolean = true  
skin_skip      : real as length = 1 um 

logging.priority : string = "debug"

# TEST
tiles.min_row    : integer = 50
tiles.max_row    : integer = 51
tiles.min_column : integer = 4
tiles.max_column : integer = 6
tiles.part_0     : boolean = false
tiles.part_1     : boolean = true

# end
